from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 422)
        MainWindow.setStyleSheet("alternate-background-color: rgb(30, 30, 46);\n"
"color: rgb(187, 195, 223);\n"
"background-color: rgb(30, 30, 46);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 20, 921, 31))
        self.plainTextEdit.setMouseTracking(True)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet("font: 300 12pt \"JetBrainsMono Nerd Font\";\n"
"font-color: #bdc5e2;\n"
"text-color: #bdc5e2;\n"
"")
        self.plainTextEdit.setCenterOnScroll(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 60, 951, 331))
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.scrollArea.setMouseTracking(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 935, 472))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.commandLinkButton.setMouseTracking(True)
        self.commandLinkButton.setCheckable(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout.addWidget(self.commandLinkButton)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.commandLinkButton_3.setMouseTracking(True)
        self.commandLinkButton_3.setCheckable(False)
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.verticalLayout.addWidget(self.commandLinkButton_3)
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.commandLinkButton_5.setMouseTracking(True)
        self.commandLinkButton_5.setCheckable(False)
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.verticalLayout.addWidget(self.commandLinkButton_5)
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.commandLinkButton_6.setMouseTracking(True)
        self.commandLinkButton_6.setCheckable(False)
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")
        self.verticalLayout.addWidget(self.commandLinkButton_6)
        self.commandLinkButton_10 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.commandLinkButton_10.setMouseTracking(True)
        self.commandLinkButton_10.setCheckable(False)
        self.commandLinkButton_10.setObjectName("commandLinkButton_10")
        self.verticalLayout.addWidget(self.commandLinkButton_10)
        self.commandLinkButton_9 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.commandLinkButton_9.setMouseTracking(True)
        self.commandLinkButton_9.setCheckable(False)
        self.commandLinkButton_9.setObjectName("commandLinkButton_9")
        self.verticalLayout.addWidget(self.commandLinkButton_9)
        self.commandLinkButton_8 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.commandLinkButton_8.setMouseTracking(True)
        self.commandLinkButton_8.setCheckable(False)
        self.commandLinkButton_8.setObjectName("commandLinkButton_8")
        self.verticalLayout.addWidget(self.commandLinkButton_8)
        self.commandLinkButton_7 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_7.setObjectName("commandLinkButton_7")
        self.verticalLayout.addWidget(self.commandLinkButton_7)
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.verticalLayout.addWidget(self.commandLinkButton_4)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(parent=self.scrollAreaWidgetContents)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.verticalLayout.addWidget(self.commandLinkButton_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plainTextEdit.setWhatsThis(_translate("MainWindow", "Enter the application you want to search here"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Enter your search"))
        self.commandLinkButton.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_5.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_6.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_10.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_9.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_8.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_7.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_4.setText(_translate("MainWindow", "CommandLinkButton"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "CommandLinkButton"))
