#!/usr/bin/env bash

# this is a script to automate opening chromium and searching the results on either google for 
# it will work in the format of chromium --new-window --incognito url+search_query+paramaters
# use 'n' for new window and 'i' tag for the icognito mode
# y for youtube
# g for google 
# fs for focused search  on only the below mentioned sites
#
# focused search parameters are mentioned below
# site:reddit.com OR site:stackoverflow.com OR site:github.com OR site:realpython.com OR site:freecodecamp.org OR site:w3schools.com OR site:stckexchange.com OR site:geeksforgeeks.org OR site:medium.com "
#
# use '-h' for getting a guide on how to use this script
#

echo "Welcome to the Search script."
echo ""

arg1="" #argument for having using the incognito
arg2="" #argument for launching a new window
arg3="https://www.youtube.com/results?search_query="  #argument having the platform to search on by default it searches on youtube
arg4="" #a possible argument for when doing focused search
search="" #search query

possible_search_platforms=("https://www.youtube.com/results?search_query=" "https://www.google.com/search?q=" "https://www.youtube.com/results?search_query=")

if [ $# -eq 0 ]; then

  read -p "Enter your search query: " search
  echo ""
  
  echo "Please choose the platform you want to search on"
  echo "'y' for youtube"
  echo "'g' for google"
  echo "'fs' for doing a focused search on google with results only from a select few sites"
  echo "Leave blank for using the default search platform 'YouTube'"
  read -p "Your choice: " choice
  echo ""

  if [[ "$choice" == "y" ]]; then
    arg3="https://www.youtube.com/results?search_query="

  elif [[ "$choice" == "g" ]]; then
      arg3="https://www.google.com/search?q="

  elif [[ "$choice" == "fs" ]]; then
      arg4="site:reddit.com OR site:stackoverflow.com OR site:github.com OR site:realpython.com OR site:freecodecamp.org OR site:w3schools.com OR site:stckexchange.com OR site:geeksforgeeks.org OR site:medium.com "
      arg3="https://www.google.com/search?q="

  elif [[ "$choice" == "" ]]; then
    echo "Using the default option 'Youtube'"

  else
    echo "Please select one and only one options from the above"
  fi

  read -p "Do you want to open this in incognito mode (i) or a new window (n)? leave it blank for neither. (i/n) " option
  echo ""
  
  if [[ "$option" == "n" ]]; then
    arg2="--new-window"
  elif [[ "$option" == "i" ]]; then
    arg1="--incognito"
  elif [[ "$option" == "in" ]] || [[ "$option" == "ni" ]]; then
    arg2="--new-window"
    arg1="--incognito"
    
  fi 
  
  search="$search "
  search="${search// /+}" #replaces all the whitespaces with '+'
  arg4="${arg4// /+}"
  chromium "$arg1" "$arg2" "$arg3""$search""$arg4" &
  echo "Searching for '$arg3$search$arg4'"
 


elif [[ "$1" == "in" ]] || [[ "$1" == "ni" ]]; then
  arg2="--new-window"
  arg1="--incognito"

  shift
  
  for arg in "$@"
  do 
    if [[ "$arg" == "fs" ]]; then
      arg4="site:reddit.com OR site:stackoverflow.com OR site:github.com OR site:realpython.com OR site:freecodecamp.org OR site:w3schools.com OR site:stckexchange.com OR site:geeksforgeeks.org OR site:medium.com "
      arg3="https://www.google.com/search?q="
 
    elif [[ "$arg" == "y" ]]; then
      arg3="https://www.youtube.com/results?search_query="

    elif [[ "$arg" == "g" ]]; then
      arg3="https://www.google.com/search?q="

    else
      search+="$arg "
    fi 
  done
    
  search="$search "
  search="${search// /+}" #replaces all the whitespaces with '+'
  arg4="${arg4// /+}"
  chromium "$arg1" "$arg2" "$arg3""$search""$arg4" &
  echo "Searching for '$arg3$search$arg4'"



else
  for arg in "$@"
  do 
    if [ "$arg" == "i" ]; then
      arg1="--incognito"

    elif [[ "$arg" == "n" ]]; then
      arg2="--new-window"

    elif [[ "$arg" == "y" ]]; then
      arg3="https://www.youtube.com/results?search_query="

    elif [[ "$arg" == "g" ]]; then
      arg3="https://www.google.com/search?q="

    elif [[ "$arg" == "fs" ]]; then
      arg4="site:reddit.com OR site:stackoverflow.com OR site:github.com OR site:realpython.com OR site:freecodecamp.org OR site:w3schools.com OR site:stckexchange.com OR site:geeksforgeeks.org OR site:medium.com "
      arg3="https://www.google.com/search?q="

    elif [[ "$arg" == "-h" ]]; then

      echo "This script helps you search your query on the internet by default if no additional option is provided it runs the search in youtube in the same window as the current open window in a new tab if no chromium window is open then it opens one."
      echo ""
      echo "Usage:"
      echo "  search [option1] [option2] .... [search query]"
      echo ""
      echo "Options:"
      echo " n     opens the query in a new window"
      echo " i     opens the query in incognito mode"
      echo ""
      echo " g     searches the query on google"
      echo " y     searches the query on youtube"
      echo " fs    (focused search) searches the query on google but with results only from a select few websites"
      echo " -h    display this help and exits"
      echo ""
      exit 0
      

    else
      search+="$arg "
    fi 
  done 

  search="${search// /+}"
  arg4="${arg4// /+}"
  chromium "$arg1" "$arg2" "$arg3""$search""$arg4"  &
  echo "Searching for '$arg3$search$arg4'"
fi

